# Generated by Django 5.2.8 on 2025-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
